import { ShiftLog, AuditLog } from './hooks/useChecklist';

export const MOCK_ACTIVE_LOGS: ShiftLog[] = [
  {
    _id: 'shift_mock_001',
    shiftDate: '2026-10-09',
    status: 'PENDING',
    progressPercentage: 62.5,
    templateId: {
      _id: 'tmpl_ops_day',
      title: 'Quy trình Trực Vận hành Ca Ngày (06:30 - 18:30)',
      sessionType: 'DURING',
      departmentId: {
        _id: 'dept_ops',
        name: 'Khối Quản lý Giao dịch & Bù trừ (QLGD & QLRR)',
        code: 'QLGD_OPS',
      },
    },
    userId: {
      _id: 'usr_hiepth',
      fullName: 'Trương Hoàng Hiệp',
      username: 'hiepth',
    },
    details: [
      {
        taskId: 'TASK_LOGIN_CHECK',
        taskNameSnapshot: 'Đăng nhập & Kiểm tra kết nối 5 hệ thống cốt lõi (M-System, VNCLEAR, CQG, LSEG, Refinitiv)',
        prioritySnapshot: 'HIGH',
        status: 'PASSED',
        isChecked: true,
        checkedAt: '2026-10-09T07:15:00.000Z',
        updatedBy: {
          _id: 'usr_hiepth',
          fullName: 'Trương Hoàng Hiệp',
          username: 'hiepth',
        },
        note: 'Kết nối ổn định, ping CQG Gateway 12ms, VNCLEAR sẵn sàng.',
        timetableSnapshot: '07:00 - 07:30',
        slaDeadlineSnapshot: '07:30',
        actionDescriptionSnapshot: 'Kiểm tra ping và session đăng nhập của 5 hệ thống đối tác sàn quốc tế.',
        urdReferenceSnapshot: 'URD-OPS-01',
        fileLocationSnapshot: 'C:\\Trading\\Logs\\HealthCheck',
      },
      {
        taskId: 'TASK_CHECK_PRICE_GTT',
        taskNameSnapshot: 'Kiểm tra Giá thanh toán (GTT) & tham chiếu ngày T',
        prioritySnapshot: 'CRITICAL',
        status: 'PASSED',
        isChecked: true,
        isBotCheckSnapshot: true,
        resultNote: '✓ Khớp 100% (28/28 mã HĐ, 0 lệch)',
        checkedAt: '2026-10-09T07:45:00.000Z',
        updatedBy: {
          _id: 'bot_gtt',
          fullName: 'Robot CE-CCP GTT',
          username: 'bot_runner',
        },
        note: 'Đã đối soát CoreEX vs CoreCCP không chênh lệch.',
        timetableSnapshot: '07:30 - 08:00',
        slaDeadlineSnapshot: '08:00',
        actionDescriptionSnapshot: 'Tự động đối soát bảng giá thanh toán CoreEX và CoreCCP trước giờ mở cửa.',
        urdReferenceSnapshot: 'URD-GTT-02',
      },
      {
        taskId: 'TASK_CHECK_KLGD',
        taskNameSnapshot: 'Giám sát & Đối chiếu Khớp lệnh Khối lượng giao dịch MS vs CQG trong phiên',
        prioritySnapshot: 'CRITICAL',
        status: 'PASSED',
        isChecked: true,
        isBotCheckSnapshot: true,
        resultNote: '✓ Khớp 100% (Tổng KL: 14,250 Lots | Khớp cả 2 chiều)',
        checkedAt: '2026-10-09T10:00:00.000Z',
        updatedBy: {
          _id: 'bot_klgd',
          fullName: 'Autonomous Bot (60m)',
          username: 'bot_runner',
        },
        note: 'Chu kỳ 60 phút - Khớp hoàn toàn không có lệch lot.',
        timetableSnapshot: 'Mỗi 60 phút',
        frequencyMinutesSnapshot: 60,
        functionUrlSnapshot: '/trading-manager',
        actionDescriptionSnapshot: 'Bot chạy tự động 60 phút/lần so khớp tổng khối lượng khớp lệnh M-System và CQG.',
        urdReferenceSnapshot: 'URD-RECON-01',
      },
      {
        taskId: 'TASK_SCAN_NEGATIVE_MARGIN',
        taskNameSnapshot: 'Quét & Giám sát Ký quỹ Âm (Negative Margin Checker)',
        prioritySnapshot: 'HIGH',
        status: 'NEEDS_ATTENTION',
        isChecked: false,
        isBotCheckSnapshot: true,
        resultNote: '⚠ Phát hiện 02 tài khoản âm ký quỹ (003C882199, 003C991201)',
        updatedBy: {
          _id: 'bot_margin',
          fullName: 'Robot Margin Scanner',
          username: 'bot_runner',
        },
        note: 'Đã gửi thông báo cảnh báo qua Telegram cho phòng QLRR xử lý Call Margin.',
        timetableSnapshot: 'Liên tục trong phiên',
        urdReferenceSnapshot: 'URD-RISK-03',
        actionDescriptionSnapshot: 'Tự động quét danh sách tài khoản vi phạm tỷ lệ ký quỹ an toàn.',
      },
      {
        taskId: 'TASK_OMS_COREEX_STATUS',
        taskNameSnapshot: 'Kiểm tra trạng thái OMS CoreEX & luồng định tuyến lệnh',
        prioritySnapshot: 'MEDIUM',
        status: 'WAITING',
        isChecked: false,
        timetableSnapshot: '09:00 - 15:00',
        note: 'Đang theo dõi cổng định tuyến FIX LME và CME.',
        actionDescriptionSnapshot: 'Giám sát độ trễ và hàng đợi lệnh OMS CoreEX trong phiên giao dịch.',
      },
      {
        taskId: 'TASK_PRE_EOD_CHECK',
        taskNameSnapshot: 'Đối chiếu Pre-EOD 3 bên (CoreCCP vs CoreEX vs CQG)',
        prioritySnapshot: 'CRITICAL',
        status: 'PENDING',
        isChecked: false,
        isBotCheckSnapshot: true,
        resultNote: null,
        timetableSnapshot: '16:00 - 16:30',
        slaDeadlineSnapshot: '16:30',
        deadlineSnapshot: '16:30',
        actionDescriptionSnapshot: 'Chốt khớp lệnh và vị thế ròng 3 bên trước khi bước vào quy trình đóng sổ.',
        urdReferenceSnapshot: 'URD-PRE-EOD',
      },
      {
        taskId: 'TASK_CCP_STATISTICS',
        taskNameSnapshot: 'Thống kê Báo cáo Khối lượng & Giá trị bù trừ CCP (Macro CCP)',
        prioritySnapshot: 'HIGH',
        status: 'PENDING',
        isChecked: false,
        isBotCheckSnapshot: true,
        timetableSnapshot: '16:30 - 17:00',
        slaDeadlineSnapshot: '17:00',
        actionDescriptionSnapshot: 'Chạy macro tổng hợp báo cáo thanh toán bù trừ CCP theo quy chuẩn Bộ Tài chính.',
        urdReferenceSnapshot: 'URD-MACRO-CCP',
      },
      {
        taskId: 'TASK_BACKUP_FILES',
        taskNameSnapshot: 'Tải & Lưu trữ bộ 25 báo cáo sao lưu ca trực (Backup VNCLEAR Maker / M-System)',
        prioritySnapshot: 'HIGH',
        status: 'PENDING',
        isChecked: false,
        timetableSnapshot: '17:00 - 17:30',
        slaDeadlineSnapshot: '17:30',
        actionDescriptionSnapshot: 'RPA tự động tải toàn bộ 25 báo cáo nghiệp vụ và lưu trữ vào ổ đĩa Backup ca trực.',
        urdReferenceSnapshot: 'URD-BACKUP-04',
      },
    ],
  },
  {
    _id: 'shift_mock_002',
    shiftDate: '2026-10-09',
    status: 'PENDING',
    progressPercentage: 20.0,
    templateId: {
      _id: 'tmpl_ops_night',
      title: 'Quy trình Trực Vận hành Ca Tối (18:30 - 06:30)',
      sessionType: 'CLOSE',
      departmentId: {
        _id: 'dept_ops',
        name: 'Khối Quản lý Giao dịch & Bù trừ (QLGD & QLRR)',
        code: 'QLGD_OPS',
      },
    },
    userId: {
      _id: 'usr_truonghh',
      fullName: 'Trương Hoàng Hiệp (Ca đêm)',
      username: 'hiepth',
    },
    details: [],
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    _id: 'audit_01',
    taskId: 'TASK_CHECK_KLGD',
    taskName: 'Giám sát & Đối chiếu Khớp lệnh Khối lượng giao dịch MS vs CQG',
    userId: { fullName: 'Autonomous Bot (60m)', username: 'bot_runner' },
    action: 'STATUS_UPDATE',
    details: 'Chuyển trạng thái sang PASSED (Khớp 100% 14,250 Lots)',
    createdAt: '2026-10-09T10:00:15.000Z',
  },
  {
    _id: 'audit_02',
    taskId: 'TASK_SCAN_NEGATIVE_MARGIN',
    taskName: 'Quét & Giám sát Ký quỹ Âm (Negative Margin Checker)',
    userId: { fullName: 'Robot Margin Scanner', username: 'bot_runner' },
    action: 'STATUS_UPDATE',
    details: 'Chuyển trạng thái sang NEEDS_ATTENTION (Phát hiện 2 TK vi phạm)',
    createdAt: '2026-10-09T09:30:20.000Z',
  },
  {
    _id: 'audit_03',
    taskId: 'TASK_CHECK_PRICE_GTT',
    taskName: 'Kiểm tra Giá thanh toán (GTT) & tham chiếu ngày T',
    userId: { fullName: 'Robot CE-CCP GTT', username: 'bot_runner' },
    action: 'CHECK',
    details: 'Xác nhận Đạt (Khớp 28/28 mã HĐ)',
    createdAt: '2026-10-09T07:45:10.000Z',
  },
  {
    _id: 'audit_04',
    taskId: 'TASK_LOGIN_CHECK',
    taskName: 'Đăng nhập & Kiểm tra kết nối 5 hệ thống cốt lõi',
    userId: { fullName: 'Trương Hoàng Hiệp', username: 'hiepth' },
    action: 'CHECK',
    details: 'Xác nhận kiểm tra thành công lúc 07:15',
    createdAt: '2026-10-09T07:15:22.000Z',
  },
];
