export const DEFAULT_LME_CODES = {
  LALZ: 'AHD',
  LDKZ: 'CAD',
  LEDZ: 'PBD',
  LNIZ: 'NID',
  LTIZ: 'SND',
  LZHZ: 'ZDS',
};

export const DEFAULT_MONTH_CODES = {
  F: '1',
  G: '2',
  H: '3',
  J: '4',
  K: '5',
  M: '6',
  N: '7',
  Q: '8',
  U: '9',
  V: '10',
  X: '11',
  Z: '12',
};

export const DEFAULT_COMMODITIES = [
  {
    MaHangHoa: 'ALI',
    TenHangHoa: 'Nhôm COMEX',
    NhomHH: 'Kim loại',
    TienTe: 'USD',
    DonViHD: 'Tonnes',
    DonViYetGia: '1',
    DoLonHD: '25',
    BuocGiaToiThieu: '0.25',
  },
  {
    MaHangHoa: 'BM',
    TenHangHoa: 'Dầu Brent mini',
    NhomHH: 'Năng lượng',
    TienTe: 'USD',
    DonViHD: 'Barrels',
    DonViYetGia: '1',
    DoLonHD: '100',
    BuocGiaToiThieu: '0.01',
  },
  {
    MaHangHoa: 'CCE',
    TenHangHoa: 'Ca cao',
    NhomHH: 'Nguyên liệu công nghiệp',
    TienTe: 'USD',
    DonViHD: 'Tonnes',
    DonViYetGia: '1',
    DoLonHD: '10',
    BuocGiaToiThieu: '1',
  },
  {
    MaHangHoa: 'CLE',
    TenHangHoa: 'Dầu WTI',
    NhomHH: 'Năng lượng',
    TienTe: 'USD',
    DonViHD: 'Barrels',
    DonViYetGia: '1',
    DoLonHD: '1000',
    BuocGiaToiThieu: '0.01',
  },
  {
    MaHangHoa: 'CPE',
    TenHangHoa: 'Đồng',
    NhomHH: 'Kim loại',
    TienTe: 'USD',
    DonViHD: 'lbs',
    DonViYetGia: '1',
    DoLonHD: '25000',
    BuocGiaToiThieu: '0.0005',
  },
  {
    MaHangHoa: 'CTE',
    TenHangHoa: 'Bông sợi',
    NhomHH: 'Nguyên liệu công nghiệp',
    TienTe: 'USD',
    DonViHD: 'lbs',
    DonViYetGia: '0.01',
    DoLonHD: '50000',
    BuocGiaToiThieu: '0.01',
  },
  {
    MaHangHoa: 'FEF',
    TenHangHoa: 'Quặng sắt',
    NhomHH: 'Kim loại',
    TienTe: 'USD',
    DonViHD: 'Tonnes',
    DonViYetGia: '1',
    DoLonHD: '100',
    BuocGiaToiThieu: '0.01',
  },
  {
    MaHangHoa: 'KCE',
    TenHangHoa: 'Cà phê Arabica',
    NhomHH: 'Nguyên liệu công nghiệp',
    TienTe: 'USD',
    DonViHD: 'pounds',
    DonViYetGia: '0.01',
    DoLonHD: '37500',
    BuocGiaToiThieu: '0.05',
  },
  {
    MaHangHoa: 'KWE',
    TenHangHoa: 'Lúa mỳ Kansas',
    NhomHH: 'Nông sản',
    TienTe: 'USD',
    DonViHD: 'Bushels',
    DonViYetGia: '0.01',
    DoLonHD: '5000',
    BuocGiaToiThieu: '0.25',
  },
  {
    MaHangHoa: 'LRC',
    TenHangHoa: 'Cà phê Robusta',
    NhomHH: 'Nguyên liệu công nghiệp',
    TienTe: 'USD',
    DonViHD: 'Tonnes',
    DonViYetGia: '1',
    DoLonHD: '10',
    BuocGiaToiThieu: '1',
  },
  {
    MaHangHoa: 'MCLE',
    TenHangHoa: 'Dầu WTI micro',
    NhomHH: 'Năng lượng',
    TienTe: 'USD',
    DonViHD: 'Barrels',
    DonViYetGia: '1',
    DoLonHD: '100',
    BuocGiaToiThieu: '0.01',
  },
  {
    MaHangHoa: 'MHG',
    TenHangHoa: 'Đồng micro',
    NhomHH: 'Kim loại',
    TienTe: 'USD',
    DonViHD: 'lbs',
    DonViYetGia: '1',
    DoLonHD: '2500',
    BuocGiaToiThieu: '0.0005',
  },
  {
    MaHangHoa: 'MPO',
    TenHangHoa: 'Dầu cọ thô',
    NhomHH: 'Nguyên liệu công nghiệp',
    TienTe: 'MYR',
    DonViHD: 'metrics Tons',
    DonViYetGia: '1',
    DoLonHD: '25',
    BuocGiaToiThieu: '1',
  },
  {
    MaHangHoa: 'MQC',
    TenHangHoa: 'Đồng mini',
    NhomHH: 'Kim loại',
    TienTe: 'USD',
    DonViHD: 'Pounds',
    DonViYetGia: '1',
    DoLonHD: '12500',
    BuocGiaToiThieu: '0.002',
  },
  {
    MaHangHoa: 'MQI',
    TenHangHoa: 'Bạc mini',
    NhomHH: 'Kim loại',
    TienTe: 'USD',
    DonViHD: 'Troy ounces',
    DonViYetGia: '1',
    DoLonHD: '2500',
    BuocGiaToiThieu: '0.0125',
  },
  {
    MaHangHoa: 'MZC',
    TenHangHoa: 'Ngô micro',
    NhomHH: 'Nông sản',
    TienTe: 'USD',
    DonViHD: 'Bushels',
    DonViYetGia: '0.01',
    DoLonHD: '500',
    BuocGiaToiThieu: '0.5',
  },
  {
    MaHangHoa: 'MZL',
    TenHangHoa: 'Dầu đậu tương micro',
    NhomHH: 'Nông sản',
    TienTe: 'USD',
    DonViHD: 'Pounds',
    DonViYetGia: '0.01',
    DoLonHD: '6000',
    BuocGiaToiThieu: '0.02',
  },
  {
    MaHangHoa: 'MZM',
    TenHangHoa: 'Khô đậu tương micro',
    NhomHH: 'Nông sản',
    TienTe: 'USD',
    DonViHD: 'Short Tons',
    DonViYetGia: '1',
    DoLonHD: '10',
    BuocGiaToiThieu: '0.2',
  },
  {
    MaHangHoa: 'MZS',
    TenHangHoa: 'Đậu tương micro',
    NhomHH: 'Nông sản',
    TienTe: 'USD',
    DonViHD: 'Bushels',
    DonViYetGia: '0.01',
    DoLonHD: '500',
    BuocGiaToiThieu: '0.5',
  },
  {
    MaHangHoa: 'MZW',
    TenHangHoa: 'Lúa mỳ micro',
    NhomHH: 'Nông sản',
    TienTe: 'USD',
    DonViHD: 'Bushels',
    DonViYetGia: '0.01',
    DoLonHD: '500',
    BuocGiaToiThieu: '0.5',
  },
  {
    MaHangHoa: 'NGE',
    TenHangHoa: 'Khí tự nhiên',
    NhomHH: 'Năng lượng',
    TienTe: 'USD',
    DonViHD: 'MM BTU',
    DonViYetGia: '1',
    DoLonHD: '10000',
    BuocGiaToiThieu: '0.001',
  },
  {
    MaHangHoa: 'NQG',
    TenHangHoa: 'Khí tự nhiên mini',
    NhomHH: 'Năng lượng',
    TienTe: 'USD',
    DonViHD: 'MM BTU',
    DonViYetGia: '1',
    DoLonHD: '2500',
    BuocGiaToiThieu: '0.005',
  },
  {
    MaHangHoa: 'NQM',
    TenHangHoa: 'Dầu WTI Mini',
    NhomHH: 'Năng lượng',
    TienTe: 'USD',
    DonViHD: 'Barrels',
    DonViYetGia: '1',
    DoLonHD: '500',
    BuocGiaToiThieu: '0.025',
  },
  {
    MaHangHoa: 'PLE',
    TenHangHoa: 'Bạch kim',
    NhomHH: 'Kim loại',
    TienTe: 'USD',
    DonViHD: 'Troy ounces',
    DonViYetGia: '1',
    DoLonHD: '50',
    BuocGiaToiThieu: '0.1',
  },
  {
    MaHangHoa: 'QO',
    TenHangHoa: 'Dầu Brent',
    NhomHH: 'Năng lượng',
    TienTe: 'USD',
    DonViHD: 'Barrels',
    DonViYetGia: '1',
    DoLonHD: '1000',
    BuocGiaToiThieu: '0.01',
  },
  {
    MaHangHoa: 'QP',
    TenHangHoa: 'Dầu ít lưu huỳnh',
    NhomHH: 'Năng lượng',
    TienTe: 'USD',
    DonViHD: 'Tonnes',
    DonViYetGia: '1',
    DoLonHD: '100',
    BuocGiaToiThieu: '0.25',
  },
  {
    MaHangHoa: 'QW',
    TenHangHoa: 'Đường trắng',
    NhomHH: 'Nguyên liệu công nghiệp',
    TienTe: 'USD',
    DonViHD: 'Tonnes',
    DonViYetGia: '1',
    DoLonHD: '50',
    BuocGiaToiThieu: '0.1',
  },
  {
    MaHangHoa: 'RBE',
    TenHangHoa: 'Xăng RBOB',
    NhomHH: 'Năng lượng',
    TienTe: 'USD',
    DonViHD: 'gallons',
    DonViYetGia: '1',
    DoLonHD: '42000',
    BuocGiaToiThieu: '0.0001',
  },
  {
    MaHangHoa: 'SBE',
    TenHangHoa: 'Đường 11',
    NhomHH: 'Nguyên liệu công nghiệp',
    TienTe: 'USD',
    DonViHD: 'Pounds',
    DonViYetGia: '0.01',
    DoLonHD: '112000',
    BuocGiaToiThieu: '0.01',
  },
  {
    MaHangHoa: 'SIE',
    TenHangHoa: 'Bạc',
    NhomHH: 'Kim loại',
    TienTe: 'USD',
    DonViHD: 'Troy ounces',
    DonViYetGia: '1',
    DoLonHD: '5000',
    BuocGiaToiThieu: '0.001',
  },
  {
    MaHangHoa: 'SIL',
    TenHangHoa: 'Bạc micro',
    NhomHH: 'Kim loại',
    TienTe: 'USD',
    DonViHD: 'Troy ounces',
    DonViYetGia: '1',
    DoLonHD: '1000',
    BuocGiaToiThieu: '0.005',
  },
  {
    MaHangHoa: 'TRU',
    TenHangHoa: 'Cao su RSS3',
    NhomHH: 'Nguyên liệu công nghiệp',
    TienTe: 'JPY',
    DonViHD: 'kg',
    DonViYetGia: '1',
    DoLonHD: '5000',
    BuocGiaToiThieu: '0.1',
  },
  {
    MaHangHoa: 'XB',
    TenHangHoa: 'Đậu Tương Mini',
    NhomHH: 'Nông sản',
    TienTe: 'USD',
    DonViHD: 'Bushels',
    DonViYetGia: '0.01',
    DoLonHD: '1000',
    BuocGiaToiThieu: '0.125',
  },
  {
    MaHangHoa: 'XC',
    TenHangHoa: 'Ngô Mini',
    NhomHH: 'Nông sản',
    TienTe: 'USD',
    DonViHD: 'Bushels',
    DonViYetGia: '0.01',
    DoLonHD: '1000',
    BuocGiaToiThieu: '0.125',
  },
  {
    MaHangHoa: 'XW',
    TenHangHoa: 'Lúa Mỳ Mini',
    NhomHH: 'Nông sản',
    TienTe: 'USD',
    DonViHD: 'Bushels',
    DonViYetGia: '0.01',
    DoLonHD: '1000',
    BuocGiaToiThieu: '0.125',
  },
  {
    MaHangHoa: 'ZCE',
    TenHangHoa: 'Ngô',
    NhomHH: 'Nông sản',
    TienTe: 'USD',
    DonViHD: 'Bushels',
    DonViYetGia: '0.01',
    DoLonHD: '5000',
    BuocGiaToiThieu: '0.25',
  },
  {
    MaHangHoa: 'ZFT',
    TenHangHoa: 'Cao su TSR20',
    NhomHH: 'Nguyên liệu công nghiệp',
    TienTe: 'USD',
    DonViHD: 'Tonnes',
    DonViYetGia: '10',
    DoLonHD: '5',
    BuocGiaToiThieu: '0.1',
  },
  {
    MaHangHoa: 'ZLE',
    TenHangHoa: 'Dầu Đậu Tương',
    NhomHH: 'Nông sản',
    TienTe: 'USD',
    DonViHD: 'lbs',
    DonViYetGia: '0.01',
    DoLonHD: '60000',
    BuocGiaToiThieu: '0.01',
  },
  {
    MaHangHoa: 'ZME',
    TenHangHoa: 'Khô Đậu Tương',
    NhomHH: 'Nông sản',
    TienTe: 'USD',
    DonViHD: 'Tons',
    DonViYetGia: '1',
    DoLonHD: '100',
    BuocGiaToiThieu: '0.1',
  },
  {
    MaHangHoa: 'ZRE',
    TenHangHoa: 'Gạo thô',
    NhomHH: 'Nông sản',
    TienTe: 'USD',
    DonViHD: 'lbs',
    DonViYetGia: '0.01',
    DoLonHD: '200000',
    BuocGiaToiThieu: '0.005',
  },
  {
    MaHangHoa: 'ZSE',
    TenHangHoa: 'Đậu Tương',
    NhomHH: 'Nông sản',
    TienTe: 'USD',
    DonViHD: 'Bushels',
    DonViYetGia: '0.01',
    DoLonHD: '5000',
    BuocGiaToiThieu: '0.25',
  },
  {
    MaHangHoa: 'ZWA',
    TenHangHoa: 'Lúa Mỳ',
    NhomHH: 'Nông sản',
    TienTe: 'USD',
    DonViHD: 'Bushels',
    DonViYetGia: '0.01',
    DoLonHD: '5000',
    BuocGiaToiThieu: '0.25',
  },
  {
    MaHangHoa: 'LALZ',
    TenHangHoa: 'Nhôm LME',
    NhomHH: 'Kim loại',
    TienTe: 'USD',
    DonViHD: 'Tonnes (with a tolerance of +/- 2%)',
    DonViYetGia: '1',
    DoLonHD: '25',
    BuocGiaToiThieu: '0.5',
  },
  {
    MaHangHoa: 'LDKZ',
    TenHangHoa: 'Đồng LME',
    NhomHH: 'Kim loại',
    TienTe: 'USD',
    DonViHD: 'Tonnes (with a tolerance of +/- 2%)',
    DonViYetGia: '1',
    DoLonHD: '25',
    BuocGiaToiThieu: '0.5',
  },
  {
    MaHangHoa: 'LEDZ',
    TenHangHoa: 'Chì LME',
    NhomHH: 'Kim loại',
    TienTe: 'USD',
    DonViHD: 'Tonnes (with a tolerance of +/- 2%)',
    DonViYetGia: '1',
    DoLonHD: '25',
    BuocGiaToiThieu: '0.5',
  },
  {
    MaHangHoa: 'LHC',
    TenHangHoa: 'Thép cuộn cán nóng FOB Trung Quốc',
    NhomHH: 'Kim loại',
    TienTe: 'USD',
    DonViHD: 'Tonnes',
    DonViYetGia: '1',
    DoLonHD: '10',
    BuocGiaToiThieu: '0.5',
  },
  {
    MaHangHoa: 'LNIZ',
    TenHangHoa: 'Nickel LME',
    NhomHH: 'Kim loại',
    TienTe: 'USD',
    DonViHD: 'Tonnes (with a tolerance of +/- 2%)',
    DonViYetGia: '1',
    DoLonHD: '6',
    BuocGiaToiThieu: '5',
  },
  {
    MaHangHoa: 'LTIZ',
    TenHangHoa: 'Thiếc LME',
    NhomHH: 'Kim loại',
    TienTe: 'USD',
    DonViHD: 'Tonnes',
    DonViYetGia: '1',
    DoLonHD: '5',
    BuocGiaToiThieu: '5',
  },
  {
    MaHangHoa: 'LZHZ',
    TenHangHoa: 'Kẽm LME',
    NhomHH: 'Kim loại',
    TienTe: 'USD',
    DonViHD: 'Tonnes (with a tolerance of +/- 2%)',
    DonViYetGia: '1',
    DoLonHD: '25',
    BuocGiaToiThieu: '0.5',
  },
  {
    MaHangHoa: 'SSC',
    TenHangHoa: 'Thép phế liệu CFR Thổ Nhĩ Kỳ',
    NhomHH: 'Kim loại',
    TienTe: 'USD',
    DonViHD: 'Tonnes',
    DonViYetGia: '1',
    DoLonHD: '10',
    BuocGiaToiThieu: '0.5',
  },
  {
    MaHangHoa: 'SSR',
    TenHangHoa: 'Thép thanh vằn FOB Thổ Nhĩ Kỳ',
    NhomHH: 'Kim loại',
    TienTe: 'USD',
    DonViHD: 'Tonnes',
    DonViYetGia: '1',
    DoLonHD: '10',
    BuocGiaToiThieu: '0.5',
  },
  {
    MaHangHoa: 'C.CLE',
    TenHangHoa: 'Quyền chọn mua Dầu WTI',
    NhomHH: 'Năng lượng',
    TienTe: 'USD',
    DonViHD: 'Barrels',
    DonViYetGia: '1',
    DoLonHD: '1000',
    BuocGiaToiThieu: '0.01',
  },
  {
    MaHangHoa: 'C.KCE',
    TenHangHoa: 'Quyền chọn mua Cà phê Arabica',
    NhomHH: 'Nguyên liệu công nghiệp',
    TienTe: 'USD',
    DonViHD: 'pounds',
    DonViYetGia: '0.01',
    DoLonHD: '37500',
    BuocGiaToiThieu: '0.01',
  },
  {
    MaHangHoa: 'C.NGE',
    TenHangHoa: 'Quyền chọn mua Khí tự nhiên',
    NhomHH: 'Năng lượng',
    TienTe: 'USD',
    DonViHD: 'MM BTU',
    DonViYetGia: '1',
    DoLonHD: '10000',
    BuocGiaToiThieu: '0.001',
  },
  {
    MaHangHoa: 'C.QO',
    TenHangHoa: 'Quyền chọn mua Dầu thô Brent',
    NhomHH: 'Năng lượng',
    TienTe: 'USD',
    DonViHD: 'Barrels',
    DonViYetGia: '1',
    DoLonHD: '1000',
    BuocGiaToiThieu: '0.01',
  },
  {
    MaHangHoa: 'C.SBE',
    TenHangHoa: 'Quyền chọn mua Đường 11',
    NhomHH: 'Nguyên liệu công nghiệp',
    TienTe: 'USD',
    DonViHD: 'Pounds',
    DonViYetGia: '0.01',
    DoLonHD: '112000',
    BuocGiaToiThieu: '0.01',
  },
  {
    MaHangHoa: 'C.ZCE',
    TenHangHoa: 'Quyền chọn mua Ngô',
    NhomHH: 'Nông sản',
    TienTe: 'USD',
    DonViHD: 'Bushels',
    DonViYetGia: '0.01',
    DoLonHD: '5000',
    BuocGiaToiThieu: '0.125',
  },
  {
    MaHangHoa: 'C.ZSE',
    TenHangHoa: 'Quyền chọn mua Đậu Tương',
    NhomHH: 'Nông sản',
    TienTe: 'USD',
    DonViHD: 'Bushels',
    DonViYetGia: '0.01',
    DoLonHD: '5000',
    BuocGiaToiThieu: '0.125',
  },
  {
    MaHangHoa: 'C.ZWA',
    TenHangHoa: 'Quyền chọn mua Lúa Mỳ',
    NhomHH: 'Nông sản',
    TienTe: 'USD',
    DonViHD: 'Bushels',
    DonViYetGia: '0.01',
    DoLonHD: '5000',
    BuocGiaToiThieu: '0.125',
  },
  {
    MaHangHoa: 'P.CLE',
    TenHangHoa: 'Quyền chọn bán Dầu WTI',
    NhomHH: 'Năng lượng',
    TienTe: 'USD',
    DonViHD: 'Barrels',
    DonViYetGia: '1',
    DoLonHD: '1000',
    BuocGiaToiThieu: '0.01',
  },
  {
    MaHangHoa: 'P.KCE',
    TenHangHoa: 'Quyền chọn bán Cà phê Arabica',
    NhomHH: 'Nguyên liệu công nghiệp',
    TienTe: 'USD',
    DonViHD: 'pounds',
    DonViYetGia: '0.01',
    DoLonHD: '37500',
    BuocGiaToiThieu: '0.01',
  },
  {
    MaHangHoa: 'P.NGE',
    TenHangHoa: 'Quyền chọn bán Khí tự nhiên',
    NhomHH: 'Năng lượng',
    TienTe: 'USD',
    DonViHD: 'MM BTU',
    DonViYetGia: '1',
    DoLonHD: '10000',
    BuocGiaToiThieu: '0.001',
  },
  {
    MaHangHoa: 'P.QO',
    TenHangHoa: 'Quyền chọn bán Dầu thô Brent',
    NhomHH: 'Năng lượng',
    TienTe: 'USD',
    DonViHD: 'Barrels',
    DonViYetGia: '1',
    DoLonHD: '1000',
    BuocGiaToiThieu: '0.01',
  },
  {
    MaHangHoa: 'P.SBE',
    TenHangHoa: 'Quyền chọn bán Đường 11',
    NhomHH: 'Nguyên liệu công nghiệp',
    TienTe: 'USD',
    DonViHD: 'Pounds',
    DonViYetGia: '0.01',
    DoLonHD: '112000',
    BuocGiaToiThieu: '0.01',
  },
  {
    MaHangHoa: 'P.ZCE',
    TenHangHoa: 'Quyền chọn bán Ngô',
    NhomHH: 'Nông sản',
    TienTe: 'USD',
    DonViHD: 'Bushels',
    DonViYetGia: '0.01',
    DoLonHD: '5000',
    BuocGiaToiThieu: '0.125',
  },
  {
    MaHangHoa: 'P.ZSE',
    TenHangHoa: 'Quyền chọn bán Đậu Tương',
    NhomHH: 'Nông sản',
    TienTe: 'USD',
    DonViHD: 'Bushels',
    DonViYetGia: '0.01',
    DoLonHD: '5000',
    BuocGiaToiThieu: '0.125',
  },
  {
    MaHangHoa: 'P.ZWA',
    TenHangHoa: 'Quyền chọn bán Lúa Mỳ',
    NhomHH: 'Nông sản',
    TienTe: 'USD',
    DonViHD: 'Bushels',
    DonViYetGia: '0.01',
    DoLonHD: '5000',
    BuocGiaToiThieu: '0.125',
  },
  {
    MaHangHoa: 'CP2CO',
    TenHangHoa: 'Đồng Nano ACM',
    NhomHH: 'Kim loại',
    TienTe: 'USD',
    DonViHD: 'lbs',
    DonViYetGia: '1',
    DoLonHD: '1000',
    BuocGiaToiThieu: '0.0005',
  },
  {
    MaHangHoa: 'PL1NY',
    TenHangHoa: 'Bạch kim Nano ACM',
    NhomHH: 'Kim loại',
    TienTe: 'USD',
    DonViHD: 'Troy ounces',
    DonViYetGia: '1',
    DoLonHD: '5',
    BuocGiaToiThieu: '0.1',
  },
  {
    MaHangHoa: 'SI5CO',
    TenHangHoa: 'Bạc Nano ACM',
    NhomHH: 'Kim loại',
    TienTe: 'USD',
    DonViHD: 'Troy ounces',
    DonViYetGia: '1',
    DoLonHD: '100',
    BuocGiaToiThieu: '0.005',
  },
];

export const DEFAULT_MEMBERS = [
  {
    MaTVKD: '001',
    TenTVKD: 'Công ty TNHH Đầu tư quốc tế Hữu Nghị',
    LoaiHH: ['ACM', 'Spread', 'LME', 'Option'],
  },
  {
    MaTVKD: '002',
    TenTVKD: 'Công ty Cổ phần SaiGon Futures',
    LoaiHH: ['Spread', 'Option'],
  },
  {
    MaTVKD: '003',
    TenTVKD: 'Công Ty Cổ Phần Giao Dịch Hàng Hóa Gia Cát Lợi',
    LoaiHH: ['ACM', 'Option'],
  },
  {
    MaTVKD: '007',
    TenTVKD: 'Công ty TNHH Đầu tư Giao dịch Hàng hóa TVT',
    LoaiHH: ['Option'],
  },
  {
    MaTVKD: '009',
    TenTVKD: 'Công ty Cổ phần Tập đoàn HT Việt Nam',
    LoaiHH: ['Option'],
  },
  {
    MaTVKD: '011',
    TenTVKD: 'Công ty Cổ phần Giao dịch hàng hóa Vmex',
    LoaiHH: ['Option'],
  },
  {
    MaTVKD: '012',
    TenTVKD: 'Công ty Cổ phần Giao dịch Hàng hóa TP Hồ Chí Minh',
    LoaiHH: ['Option'],
  },
  {
    MaTVKD: '023',
    TenTVKD: 'Công ty cổ phần tư vấn đầu tư và quản lý tài sản Dsmart',
    LoaiHH: ['Option'],
  },
  {
    MaTVKD: '036',
    TenTVKD: 'Công ty cổ phần Hitech Finance',
    LoaiHH: ['Option'],
  },
  {
    MaTVKD: '039',
    TenTVKD: 'Công ty cổ phần Giao dịch Hàng hóa Quốc tế MXL',
    LoaiHH: ['Option'],
  },
  {
    MaTVKD: '040',
    TenTVKD: 'Công ty Cổ phần thương mại AIMS Futures Việt Nam',
    LoaiHH: ['Option'],
  },
  {
    MaTVKD: '041',
    TenTVKD: 'CTCP Tập Đoàn Khoáng Sản và Thương Mại VQB',
    LoaiHH: ['LME', 'Option'],
  },
  { MaTVKD: '043', TenTVKD: 'Công ty cổ phần Edu Trade', LoaiHH: ['Option'] },
  {
    MaTVKD: '045',
    TenTVKD: 'Công ty cổ phần Giao dịch Hàng hoá Đông Nam Á',
    LoaiHH: ['ACM', 'Option'],
  },
  {
    MaTVKD: '046',
    TenTVKD: 'Công ty cổ phần đầu tư SFVN',
    LoaiHH: ['ACM', 'Option'],
  },
  {
    MaTVKD: '048',
    TenTVKD: 'Công ty Cổ phần Truyền thông và Dịch vụ số Kiến Lửa',
    LoaiHH: ['Option'],
  },
  {
    MaTVKD: '059',
    TenTVKD: 'Công ty Cổ phần Đầu tư và Giao dịch phái sinh hàng hóa Việt Nam',
    LoaiHH: ['Option'],
  },
  {
    MaTVKD: '060',
    TenTVKD: 'Công ty Cổ phần Giao dịch Hàng hóa Toàn cầu',
    LoaiHH: ['Option'],
  },
  {
    MaTVKD: '061',
    TenTVKD: 'Công ty Cổ phần Đầu tư Thương mại và Xuất nhập khẩu Nhật Linh',
    LoaiHH: ['Option'],
  },
  {
    MaTVKD: '062',
    TenTVKD: 'Công Ty Cổ Phần Giao Dịch Hàng Hóa Amber',
    LoaiHH: ['Option'],
  },
  {
    MaTVKD: '063',
    TenTVKD: 'Công ty Cổ phần đầu tư và thương mại BBV',
    LoaiHH: ['Option'],
  },
  {
    MaTVKD: '065',
    TenTVKD: 'Công ty Cổ phần Finhay Việt Nam',
    LoaiHH: ['Option'],
  },
  {
    MaTVKD: '066',
    TenTVKD: 'Công ty Cổ phần Giao dịch Hàng hóa ALIA',
    LoaiHH: ['Option'],
  },
  { MaTVKD: '068', TenTVKD: 'Công ty TNHH Anfin', LoaiHH: ['ACM', 'Option'] },
  {
    MaTVKD: '069',
    TenTVKD: 'Công ty Cổ phần Harami-Trade',
    LoaiHH: ['Option'],
  },
  {
    MaTVKD: '070',
    TenTVKD: 'Công ty Cổ phần Đầu tư Phát Đạt Holdings',
    LoaiHH: ['Option'],
  },
  {
    MaTVKD: '071',
    TenTVKD: 'Công ty Cổ phần Đầu tư và kinh doanh hàng hóa Tornado',
    LoaiHH: ['ACM', 'Option'],
  },
  {
    MaTVKD: '072',
    TenTVKD: 'Công ty Cổ phần giao dịch hàng hóa 3D',
    LoaiHH: ['Option'],
  },
  {
    MaTVKD: '073',
    TenTVKD: 'Công ty Cổ Phần Giao Dịch Hàng Hoá An Thành',
    LoaiHH: ['Option'],
  },
  {
    MaTVKD: '075',
    TenTVKD: 'Công ty cổ phần giao dịch hàng hóa quốc tế SFV',
    LoaiHH: ['ACM', 'Spread', 'LME', 'Option'],
  },
  {
    MaTVKD: '076',
    TenTVKD: 'Công ty Cổ phần Đầu tư Hàng hoá Sài Gòn',
    LoaiHH: ['ACM', 'Spread', 'LME', 'Option'],
  },
];
